# Generated by Django 4.2.3 on 2023-08-01 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liste',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liste',
            name='type',
            field=models.CharField(choices=[('REC', 'Records'), ('CLO', 'Clothing'), ('POS', 'Posters'), ('MIS', 'Miscellaneous')], default='REC', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liste',
            name='year',
            field=models.IntegerField(default=2010, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2023)]),
            preserve_default=False,
        ),
    ]
