# Generated by Django 4.2.3 on 2023-08-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_liste_description_liste_sold_liste_type_liste_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
