# Generated by Django 4.2.3 on 2023-08-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_liste_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='like_new',
            field=models.BooleanField(default=True),
        ),
    ]
